### ISSUE TITLE
Artifact successfully uploaded but cannot be downloaded by client.

### ISSUE THREAD

**Issue by alexmirrington** [wandb/client#1238]
* Weights and Biases version: `0.10.0`,`0.9.7`
* Python version: `3.8.5`
* Operating System: Arch Linux x86_64 (5.8.8-arch1-1)

### Description

Creating an artifact on one machine (`wandb` version `0.10.0`)  over an SSH session with VPN connection allowed the artifact to be uploaded to the cloud, and a training run could be started on that machine from the newly synced artifact. Trying to start a training run on a different machineusing the same artifact version failed  (`wandb` version `0.10.0`), as the artifact could not be fetched. All artifact files are present in the web client, and can be downloaded from the artifacts tab. In addition, the `wandb` CLI client cannot download the artifact, and downgrading the CLI client on the second machine to `0.9.7` does not fix the issue.

### Details

Starting a training run with `wandb` version `0.10.0` yields the following stacktrace:

```
...
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/wandb/apis/public.py", line 2281, in download
    pool.map(partial(self._download_file, dirpath=dirpath), manifest.entries)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/wandb/apis/public.py", line 2314, in _download_file
    return self.get_path(name).download(dirpath)
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/wandb/apis/public.py", line 2236, in download
    cache_path = storage_policy.load_file(self, name, manifest.entries[name])
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 409, in load_file
    response = self._session.get(
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

After downgrading the CLI client to `0.9.7`, a different, but perhaps more useful error occurs:

```
...
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/wandb/apis/public.py", line 2245, in download
    pool.map(partial(self._download_file, dirpath=dirpath), manifest.entries)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/wandb/apis/public.py", line 2281, in _download_file
    return artifact_entry.download(dirpath)
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/wandb/apis/public.py", line 2200, in download
    cache_path = storage_policy.load_file(self, name, manifest.entries[name])
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/wandb/artifacts.py", line 536, in load_file
    response.raise_for_status()
  File "~/.virtualenvs/python-latest/lib/python3.8/site-packages/requests-2.24.0-py3.8.egg/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-artifacts-prod/alexmirrington/wandb_artifacts/objs/4bde5***************************?Expires=1600263353&GoogleAccessId=gorilla-cloud-storage%40wandb-production.iam.gserviceaccount.com&Signature=**************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
```

Trying to download the artifact from the CLI yields similar stacktraces.

**Comment by annirudh** [comment]
Hi @alexmirrington, thanks so much reporting this issue. I've been able to reproduce the issue and have a line on the fix. The issue will be resolved in the next CLI release.

Really sorry for the inconvenience.

**Comment by annirudh** [comment]
This issue has been resolved in CLI 0.10.1. Upgrading to the latest CLI should allow you to download artifacts successfully.

**Comment by FelipeAdachi** [comment]
Hi! for both 0.10.1 and 0.10.2 the issue remains for me. I'm unable to download artifacts with CLI or in Python.

**Comment by vanpelt** [comment]
@FelipeAdachi can you share the error you're seeing?

**Comment by FelipeAdachi** [comment]
@vanpelt,  Sure!


The error I'm getting is:

```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-4-a9085cffb7c2> in <module>()
      4 
      5 # Download all of the files contained in the artifact.
----> 6 artifact_dir = artifact.download()
      7 
      8 # Let's take a look at the downloaded files.

8 frames
/usr/local/lib/python3.6/dist-packages/requests/models.py in raise_for_status(self)
    939 
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 
    943     def close(self):

HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-artifacts-prod/felipeadachi/simpletransformers_ner/wandb_artifacts/27681/220151/PhLoUpihyWOLYDpI9UC7xA==?Expires=1600971487&GoogleAccessId=gorilla-cloud-storage%40wandb-production.iam.gserviceaccount.com&Signature=WTjwuZePIXJScfvq4tjnU12Zs1aAroFMJMZpX3LUnifWaWpA6IR1hffPOQ75cRSU6JNjqCul63t0Q4Mjf5Lgfd5EzB%2FOvYrvk70TapTELK5MOFhzovC1on%2F9ZnFgj1EA7SNFPzsBtdTY%2BCcfnufaojTVvPZf5Ic0%2BG60W%2BnQvf%2FeCp0BX4raNhAxXCk6IfLz4AspSaeCj7QRFS3bd90mUbODtUHBxRtUG%2FVcTS3kHeSHn6WkBu6rb2anhxQJn%2FPPxEiLkAOB5qEyoX%2BCkBfB1usRHGNBBS5kjYG%2Bweobw%2BgaJr4XNDzLwGy3jZkdDU1PkqIBVgzL8sl6EYrwFA7opw%3D%3D
```

wandb version: 10.0.2
python: 3.6

I'm running it on Colab, with the following commands:
`!pip install wandb`
`import wandb`
`run = wandb.init(project='simpletransformers_ner', job_type='consumer')`
`artifact = run.use_artifact('train-test-dataset:latest')`
`artifact_dir = artifact.download()`

Thank you for your attention!
And wandb is amazing! Congratulations to the team!

**Comment by annirudh** [comment]
@FelipeAdachi Would you mind trying your colab on our dev branch for `10.0.3`?

`!pip install -qq -U git+git://github.com/wandb/client.git@master#egg=wandb`

There's a fox for an issue with the download URLs becoming stale that's included in the branch. We're aiming to ship this fix in the next release.

**Comment by FelipeAdachi** [comment]
I tried with dev branch for 10.0.3, but the same error persists.

Let me know if there is anything else I can do.

**Comment by annirudh** [comment]
I'm able to reproduce the issue. So sorry, looks like there's a separate issue that needs to be fixed. I have patch, and I'll make sure it makes it into the official `10.0.3` release.
