### ISSUE TITLE
[CLI] 

### ISSUE THREAD

**Issue by afiaka87** [wandb/client#2132]
### Involves CLI features:
- `wandb offline`
- `wandb online`
- `wandb sync`

### Video
Here is a video demonstrating the exact steps taken to illustrate the issue.
https://www.dropbox.com/s/0w2avv68h41uuvn/2021-04-28_10-18-49.mkv

### Script
You will need a dataset to use this script exactly. I have pre-prepared one [here](https://www.dropbox.com/sh/5b2qz9gjytpjgl4/AACGD7F__UoIPLKRnfun9boEa?dl=0) (CUBS) which is relatively small. Unzip the file and point the `--image_text_folder` cli arg of `train_dalle.py` at it.

```bash
#!/bin/bash

# Setup conda for the first time
conda init
source ~/.bashrc

# Create conda virtual env for test
conda create -n test_wandb_corrupted_sync

# Install (as of present) the latest version of wandb (0.10.27)
pip install wandb --upgrade

# Clone a pytorch codebase used to train with
git clone https://github.com/lucidrains/DALLE-pytorch
cd DALLE-pytorch
python setup.py install

# Go offline
wandb offline

# Begin training (you will need a GPU for the repo I listed)
python train_dalle.py --taming --truncate_captions --image_text_folder CUBS

# Try to sync (perhaps as a mistake)
wandb sync --sync-all
```
Will generate:

```sh
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sync/sync.py", line 202, in run
    ds.open_for_scan(sync_item)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/internal/datastore.py", line 99, in open_for_scan
    self._read_header()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/internal/datastore.py", line 166, in _read_header
    ident, magic, version = struct.unpack("<4sHB", header)
struct.error: unpack requires a buffer of 7 bytes
```

Trying to go back online while training continues doesn't resolve the issue:

```sh
wandb online
wandb sync --sync-all
```

Will again generate:
```sh
wandb sync --sync-all
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sync/sync.py", line 202, in run
    ds.open_for_scan(sync_item)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/internal/datastore.py", line 99, in open_for_scan
    self._read_header()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/internal/datastore.py", line 166, in _read_header
    ident, magic, version = struct.unpack("<4sHB", header)
struct.error: unpack requires a buffer of 7 bytes
```

### **Environment**
- OS: 
```sh
uname -r
5.11.0-7612-generic
```
- Docker: `pytorch/pytorch:1.8.1-cuda11.1-cudnn8-devel`
- Python Version: 3.8.5
- CUDA Toolkit 11.1
```sh
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```
- conda version: 4.10.1
- pip version 21.0.1

**Comment by afiaka87** [comment]
Ultimately I was able to sync after I stopped training.

**Comment by vanpelt** [comment]
Yep, there are known issues with doing an offline sync of a currently running run.  We would need implement locking semantics around the syncing process.  As a workaround, you should be able to copy the contents of your running run into a new directory and then perform the sync, although there may still be cases where the file isn't fully committed.

Can you share a little more about your use case where you're running offline and syncing runs mid training?

**Comment by afiaka87** [comment]
@vanpelt It's a distributed system. It has the unfortunate requirement that all internet i/o be done on a "login node", which does not have access to the GPU. You may then queue tasks to be run on GPU nodes which are not allowed to connect to the internet at all. 

As such - I've been trying to get more frequent syncs than I would if I just waited until all 20 epochs of training fininshed by manually syncing.

Is there a better solution for this? Trying to run W&B via docker on the distributed system is probably not possible - software installations require a scheduled install via an admin and I don't necessarily want to go that far.

 The only access _out_ from the GPU node that I have is via ssh. I could therefore feasibly construct an ssh tunnel with the right ports from the GPU node, through the login node, to my home computer - which is white-listed by IP address. I've seen this set-up in your documentation with regard to a _sweep controller_, but not an actual W&B job run. Do let me know if there's something similar to what I'm talking about that I may have miseed.

For now - the "copy and sync" advice is sound. I can just run 

```
watch -n 50 rsync user@remote_host:/path/to/wandb_runs ./wandb_run &> wandb_sync.log
watch -n 525 wandb sync --sync-all ./wandb_run
```

But I do think think _some_ sort of approach to this situation would be nice. It does however sound like a difficult problem to solve. 

Is there a reason there aren't locks in place on the files already? Other than that it's quite difficult to implement, I imagine? (which is totally fair)

**Comment by afiaka87** [comment]
@vanpelt please see this discussion for more context https://github.com/lucidrains/DALLE-pytorch/pull/217#issuecomment-826454489

**Comment by vanpelt** [comment]
Hey @afiaka87 we're working on making the offline sync more robust.  I'll also chime in the DALLE-pytorch ticket.

**Comment by afiaka87** [comment]
> Hey @afiaka87 we're working on making the offline sync more robust. I'll also chime in the DALLE-pytorch ticket.

I will just say this - the most advanced users of the W&B service will do word-of-mouth marketing for you if you are good to them. Ignoring concerns surrounding distributed (where effectively _all_ state of the art deep training currently takes place) is probably not a good idea and is something I've seen on the issues a lot here.

**Comment by vanpelt** [comment]
@afiaka87 we couldn't agree more.  We're actively working on better handling of more complex multi-processing environments and hope to handle the most common cases by default and provide clear instructions on how to handle more advanced scenarios.

If you have a specific distributed example that isn't working for you today, I would be happy to hop on a quick screen share or connect you with one of our engineering leads to see if we can address the issue ahead of the official improvements we're working on.

**Comment by afiaka87** [comment]
> @afiaka87 we couldn't agree more. We're actively working on better handling of more complex multi-processing environments and hope to handle the most common cases by default and provide clear instructions on how to handle more advanced scenarios.
> 
> If you have a specific distributed example that isn't working for you today, I would be happy to hop on a quick screen share or connect you with one of our engineering leads to see if we can address the issue ahead of the official improvements we're working on.

That's good to hear - I've seen more than a few comments on the issues which were outright dismissals of any proposal to support "offline". Outages - however accidental - shine a light on such things I imagine. 

I appreciate the offer to screen share - but I have in fact already found a workaround on our setup for now. 

Do you have a clearer picture of what will be supported? In an ideal world - I would just run:

```sh
wandb offline
wandb sync

$ "You are currently running offline. Runs will be synced locally until you re-enable wandb online"
```

**Comment by afiaka87** [comment]
> @afiaka87 we couldn't agree more. We're actively working on better handling of more complex multi-processing environments and hope to handle the most common cases by default and provide clear instructions on how to handle more advanced scenarios.
> 
> If you have a specific distributed example that isn't working for you today, I would be happy to hop on a quick screen share or connect you with one of our engineering leads to see if we can address the issue ahead of the official improvements we're working on.

In terms of my specific issue - the video of the issue I provided should have all the details:
https://www.dropbox.com/s/0w2avv68h41uuvn/2021-04-28_10-18-49.mkv

**Comment by vanpelt** [comment]
Hey everyone,

We just released 0.10.32 of our library that should address the issues around syncing offline runs.  I'm going to close this issue but please add comments with any errors you may be seeing with the latest release of the library.

**Comment by MartFire** [comment]
Hi, it still not working for me with 0.10.32.
Now I have the error
`.wandb file is empty (header is 0 bytes instead of the expected 7)`

**Comment by vanpelt** [comment]
@MartFire yep, that used to throw an exception and an ugly error.  Now we print a warning saying nothing has been synced yet, and retrying again should start syncing once the data's been flushed to disk.
