### ISSUE TITLE
Got `AttributeError: 'NoneType' object has no attribute 'entity'` when using artifacts in offline mode [CLI] 

### ISSUE THREAD

**Issue by diegoquintanav** [wandb/client#2286]
**Description**
Hello! I wish to use an artifact in offline mode that I have downloaded previously, and I'm getting an error, described below.

I am debugging a model, and pushing and pulling data from `wandb` is not necessary since these runs are not meant to be analyzed. I'm using the use_artifact method in my training method, but in offline mode, this is not possible. The dataset:v1 is already on disk, and I expected it would work. Is this not intended usage? what am I doing wrong? thanks!

I have the following code:
```python
import wandb

def method_with_cm():
    with wandb.init(project="camper", job_type="train") as run:
        artifact = run.use_artifact("camper-aggregate:v1", type="dataset")
        artifact_dir = artifact.download()
        print(artifact_dir)

def method_without_cm():
    run = wandb.init(project="camper", job_type="train")
    artifact = run.use_artifact("camper-aggregate:v1", type="dataset")
    artifact_dir = artifact.download()
    print(artifact_dir)
    wandb.finish()

if __name__ == "__main__":
    print("with context manager")
    method_with_cm()
    print("without context manager")
    method_without_cm()
```

```
diego@envy:~/path/to/wandb-scripts$ WANDB_MODE=online python test-offline.py
with context manager
wandb: Currently logged in as: diegoquintana (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.10.32 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.31
wandb: Syncing run lucky-deluge-175
wandb:  View project at https://wandb.ai/diegoquintana/camper
wandb:  View run at https://wandb.ai/diegoquintana/camper/runs/2ijuv1d7
wandb: Run data is saved locally in /path/to/wandb-scripts/wandb/run-20210614_125722-2ijuv1d7
wandb: Run `wandb offline` to turn off syncing.

./artifacts/camper-aggregate:v1

wandb: Waiting for W&B process to finish, PID 22439
wandb: Program ended successfully.
wandb:
wandb: Find user logs for this run at: /path/to/wandb-scripts/wandb/run-20210614_125722-2ijuv1d7/logs/debug.log
wandb: Find internal logs for this run at: /path/to/wandb-scripts/wandb/run-20210614_125722-2ijuv1d7/logs/debug-internal.log
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb:
wandb: Synced lucky-deluge-175: https://wandb.ai/diegoquintana/camper/runs/2ijuv1d7
without context manager
wandb: wandb version 0.10.32 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.31
wandb: Syncing run glad-sound-176
wandb:  View project at https://wandb.ai/diegoquintana/camper
wandb:  View run at https://wandb.ai/diegoquintana/camper/runs/287usf4y
wandb: Run data is saved locally in /path/to/wandb-scripts/wandb/run-20210614_125733-287usf4y
wandb: Run `wandb offline` to turn off syncing.

./artifacts/camper-aggregate:v1

wandb: Waiting for W&B process to finish, PID 22650
wandb: Program ended successfully.
wandb:
wandb: Find user logs for this run at: /path/to/wandb-scripts/wandb/run-20210614_125733-287usf4y/logs/debug.log
wandb: Find internal logs for this run at: /path/to/wandb-scripts/wandb/run-20210614_125733-287usf4y/logs/debug-internal.log
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb:
wandb: Synced glad-sound-176: https://wandb.ai/diegoquintana/camper/runs/287usf4y7

# in offline mode
(tfm) diego@envy:~/path/to/wandb-scripts$ WANDB_MODE=offline python test-offline.py
with context manager
wandb: W&B syncing is set to `offline` in this directory.  Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.

wandb: Waiting for W&B process to finish, PID 22939
wandb: Program failed with code 1.
wandb: Find user logs for this run at: /path/to/wandb-scripts/wandb/offline-run-20210614_125751-2lh45k04/logs/debug.log
wandb: Find internal logs for this run at: /path/to/wandb-scripts/wandb/offline-run-20210614_125751-2lh45k04/logs/debug-internal.log
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /path/to/wandb-scripts/wandb/offline-run-20210614_125751-2lh45k04
Traceback (most recent call last):
  File "/path/to/wandb-scripts/test-offline.py", line 57, in <module>
    method_with_cm()
  File "/path/to/wandb-scripts/test-offline.py", line 38, in method_with_cm
    artifact = run.use_artifact("camper-aggregate:v1", type="dataset")
  File "/home/diego/.pyenv/versions/tfm/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2015, in use_artifact
    api = internal.Api(default_settings={"entity": r.entity, "project": r.project})
```

**Wandb features**
`wandb.use_artifact`

**How to reproduce**
See the script I mentioned above

**Environment**
- Python 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33) 
- conda is managed by pyenv 1.2.14
- Linux Mint Tricia 19.3

**Comment by MandiZhao** [comment]
Looks like without context manager, the entity and project names aren't being auto-added, this should be fixed but one current work-around is specifying the full path to your desired artifact: 
```
def method_without_cm():
    run = wandb.init(project="camper", job_type="train")
    # changed the below line:
    artifact = run.use_artifact("YourEntityName/camper/camper-aggregate:v1", type="dataset")
    artifact_dir = artifact.download()
    print(artifact_dir)
    wandb.finish()
```

**Comment by diegoquintanav** [comment]
@MandiZhao in both cases (context and without context manager) I get  `' '` from `run.entity`. However, I tried `diegoquintana/camper/camper-aggregate:v1"` (assuming my entity is my username), and it downloads a copy in `$cwd` and it does not reuse the file already present in `. This happens only if I don't specify `project` and `entity` in `run`. 

```python
with wandb.init(project="camper", entity="diegoquintana", dir=PATH_WANDB) as run:
    artifact = run.use_artifact("camper-preprocess:latest", type="dataset")
    df = read(PATH_WANDB.joinpath(artifact.file()))
```

I guess that I was expecting that the `dir` argument in `init()` resolved internally the path used for artifacts. My goal is to have a unique folder where runs and artifacts are stored and use that directory from any script that uses `wandb.init` and benefit from the downloaded files. So, two things are not happening:

1. in offline mode, I can't use already downloaded files. It may be related to the second point below, but it seems like that deserves its own issue.
2. assuming there is a path, say `PATH_WANDB=~/.wandb` in my system where I have both a `wandb` and an `artifacts` folder, I wish to point any arbitrary run to these folders, to a) store run logs there and b) use artifacts that are already downloaded. The `dir` argument of `run` achieves a) but I can't find a way to achieve b).

**Comment by diegoquintanav** [comment]
I found a way to achieve b), but it's clunky

```python
    with wandb.init(project="camper", entity="diegoquintana", dir=PATH_WANDB) as run:
        artifact = run.use_artifact("camper-preprocess:latest", type="dataset")
        # artifact = run.use_artifact("diegoquintanav/camper/camper-preprocess:latest", type="dataset") # works as well, but not offline
        artifact_dir = artifact.download(root=PATH_WANDB.joinpath(artifact.file()).parent)
        artifact_filename = PATH_WANDB.joinpath(artifact.file())
        print(artifact_filename)
```

It still does not work offline though :(

**Comment by diegoquintanav** [comment]
@MandiZhao any thoughts on how to use already downloaded artifacts when in offline mode?
