### ISSUE TITLE
[Q] A few missing default parameters when doing Sweep

### ISSUE THREAD

**Issue by jihwan-jeong** [wandb/client#2564]
Hello. 

Recently, I've learned to use the Sweep function of W&B, which I found to be really cool. 
My codebase uses `Hydra` to handle various configurations and hyperparameters, while `wandb` logs the progress of learning of various components in my model. On top of that, I've written the following `sweep-halfcheetah-pets.yaml` file for sweeping various hyperparameters (currently, I'm simply using the `grid` method only).

```yaml
program: rlkit/examples/main.py

method: grid
metric:
  goal: maximize
  name: evaluation/average_returns

parameters:
  seed:
    values: [123, 456]
  algorithm:
    value: "pets"
  env:
    value: "halfcheetah"
  log_to_wandb:
    value: true
  
  overrides.horizon:
    values: [5, 15]

  overrides.population_size:
    values: [100, 200]

  overrides.planning_iters:
    values: [2, 5]

...(multiple other parameters..)

command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
```

And to generate a Sweep, I typed the following command:
```CLI
wandb sweep rlkit/examples/sweep_conf/sweep-halfcheetah-pets.yaml --project my_project
```

This generated a command (like `wandb agent jhjeong/my_project/{$sweep_id}`), which I used to generate multiple agents on a computing server to do the sweep. 

In the current sweep config file, there are roughly ~1k unique combinations of parameters that can be tried. However, only ~100 sweep runs have finished successfully, while ~900 runs have crashed. I've looked into the saved stdout of those crashed runs (as no logs were to be found in the run information on `wandb`), and found that the `env` parameter (which has to be specified, otherwise an error occurs) wasn't specified in those runs. This is really weird as I provided a single value "halfcheetah" for the parameter `env`, and there's no reason that the sweep would miss that parameter. Besides, in those runs, all the default parameter values were simply missing, while only the parameters given as a list were provided in the command line arguments. 

I wonder if this is expected behavior? IMHO, intuitively, parameters with a single default value --- specified in the sweep.yaml file --- should always be included in the command with the exact value that was given in the config file. 

Thanks for taking a look at this issue :)
-Jihwan

**Comment by dannygoldstein** [comment]
Hi @jihwan-jeong ,

I'm sorry you ran into this issue. This was a bug on our side caused by a recent change in our backend that caused constant parameters to be improperly handled in grid search sweeps. The bug was fixed at 10:43AM PT this morning, 8/19/2021. Your config should work as expected now in production. I just tried it against our cloud service and saw that it correctly passed the value of `env` as `"halfcheetah"`. 

Please reopen if you are still experiencing this issue.

Thanks!

**Comment by jihwan-jeong** [comment]
Thank you so much for such an immediate response! Very impressive :)
Okay, I'll give it another shot and come back should the problem persists.

Thanks!
