### ISSUE TITLE
Files are only uploaded at the end of run

### ISSUE THREAD

**Issue by rmst** [wandb/client#281]
* Weights and Biases version: 0.6.30
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description

This is probably by design, so it is rather a question or feature request than a bug. Is there a way to upload files throughout a run? For me that would be useful in case a run crashes and also to download model parameters and test them locally or for visualization purposes while training is still ongoing.

**Comment by vanpelt** [comment]
0.6.30 automaticallu uploads any tfevents file as the run is progressing (we also automatically launch a tensorboard instance for you in our interface!).  Because of the way cloud storage works we have to re-upload the file as it changes.  In the tfevents case we have a backoff that re-uploads only after the file has grown by 20%.  I'm thinking I add an environment variable that allows you to specify a list unix globs to apply this same logic to.  Will your files grow, or just be created?

**Comment by rmst** [comment]
I'm not using Tensorflow/Tensorboard but guess I could still name my files *.tfevents? I was mainly asking because of model checkpointing (no modifications / growing files).

**Comment by vanpelt** [comment]
Ahh I see.  I've been thinking about checkpointing recently.  Here's a sketch of the interface I imagine:

```python
wandb.init(ckpt_config={"glob": "*ckpt*", "last": 3, "best": "*best*"})

if args.resume:
    model.load(wandb.checkpoint())
```

Behind the scenes wandb would upload new files that match the glob described in **ckpt_config**.  We would only keep the latest 3 checkpoints in cloud storage.  We could then automatically download the checkpoint if you resume a training run.  In the case where you want to start a new training run from a previous runs checkpoint you could do something like:

```python
model.load(wandb.checkpoint("username/project/run_id"))
```

The **best** argument would be to specify a glob to match a single checkpoint.  The usecase would be to only write this checkpoint if the model had improved.  I wonder if the usecase of grabbing any but the latest or best checkpoint is even worth supporting...  Would this approach solve your problem?

**Comment by rmst** [comment]
Would last=3 save the last three versions of of each file the matches a glob or would it save the three most recently written files matching the glob?

I don't know if i'd need a dedicated checkpointing api. A slightly extended file api would be enough (and more general). I'm already using the file download function similar to the way .checkpoint was used in your example. The thing that seems to be missing is something like a .flush() that triggers file uploads. Or even better: a wandb.upload function. The "keep the x-most recent versions" feature isn't that important for me personally (i'm fine with just having the most recent version) but this could also be passed as an extra argument. the best model could be saved under a different file name.

**Comment by vanpelt** [comment]
Cool, I was thinking last=3 would save the 3 most recently modified files that matched the glob.  

I like the idea of a more generic file api.  We already have a `wandb.save("path" or file)` function, unfortunately that only pushes the file at the end of the run.  I think I'll make that upload the file immediately by default.  Then we could add `wandb.load("path")` to pull down the file when resuming.

Do you want this feature to resume from failure?  Would it be useful to be able to grab the most recent run with a given tag or the same model definition and pull down it's latest checkpoint?

**Comment by rmst** [comment]
Ah cool, that would be great! Resuming from failure would be great but for me (doing mostly deep RL research) it would be more complicated because I'd have to save the complete state of the learner/agent potentially include a replay memory which can be many GB large. Saving the model in case of crash / abort is currently mostly to save

**Comment by vanpelt** [comment]
Allright, I have a working prototype.  I'll push it to pypi in the next couple days, but if you want to try it you can install with: `pip install --upgrade git+git://github.com/wandb/client.git@feature/save#egg=wandb`

I made `wandb.save` accept a file name or a glob.  If the files it finds are outside of the run directory it symlinks them to it so they are saved.  It also makes them upload as they're written to by default.  There's also a `wandb.restore` function that accepts a file name.  It will download the file to the current run directory by default if it doesn't exist.  You can also restore files from other runs by passing **run_path** i.e.  username/project/run_id.  Let me know if you have any suggestions!

**Comment by rmst** [comment]
Perfect, thank you! That makes things much easier for me :) I'll try it out with my next batch of runs.

**Comment by vanpelt** [comment]
I just pushed 0.6.31, it contains the changes documented here: https://docs.wandb.com/docs/saving.html#saving-files-during-the-run

**Comment by xanderdunn** [comment]
@vanpelt In my runs I am still seeing checkpoint files uploaded only at the end of a run.  Not using tfevents. The link to the docs there doesn't work anymore, and I don't see mention of saving during the run in the [wandb.save](https://docs.wandb.com/library/python/save) doc page.

**Comment by raubitsj** [comment]
The the wandb.save() doc page says:
```
If you want to sync files as they're being written, you can specify a filename or glob in wandb.save.
```
So if you are using wandb.save() files will be synced while the run is executing.  If you have some sample code and a link to a run that isn't being synced we can look into it:

**Comment by xanderdunn** [comment]
@raubitsj Thanks, I missed that.  This is my line of code:
```python
wandb.save(os.path.join(self.checkpoint_dir, "*model-best*"))
```

Maybe my mistake is the wildcard, I'm not sure what lead me to think that was valid.

**Comment by talesa** [comment]
Hello!
I have the same problem: despite using `wandb.save` after every epoch only the first one is uploaded immediately.
My code looks as follows:
```
for epoch in tqdm.trange(args.num_epochs):
    trainer.train_epoch()
    model_path = Path(wandb.run.dir, "model.pt").absolute().__str__()
    torch.save(func_rep.state_dict(), model_path)
    wandb.save(model_path, base_path=wandb.run.dir)
```
