### ISSUE TITLE
[CLI] Failed to start wandb/lcoal image

### ISSUE THREAD

**Issue by chenshen03** [wandb/client#2883]
**Description**
I run with `docker run -it --rm -v wandb:/vol --name wandb-local wandb/local`, but not image started in the background. 
![image](https://user-images.githubusercontent.com/20432947/140475159-2045fb1e-9d11-4bed-b891-36d4583feefb.png)
Then I change command to `docker run -it --rm -v wandb:/vol --name wandb-local 489109b083ce` where `489109b083ce` is the IMAGE ID of wandb/local:latest, the following error then occurs:
![image](https://user-images.githubusercontent.com/20432947/140475567-2a6e7013-bc7e-4a0e-b1b8-9640810cd940.png)

**Wandb features**
docker run -it --rm -v wandb:/vol --name wandb-local 489109b083c

**How to reproduce**
1. docker pull wandb/local:latest
2. docker run -it --rm -v wandb:/vol --name wandb-local 489109b083ce

**Environment**
- OS: Linux
- Environment: Local Machine
- Python Version: 3.6.8

**Comment by vanpelt** [comment]
@chenshen03 this indicates that we don't have write permission to the filesystem in the container.  What version of docker and operating system are you running?

**Comment by chenshen03** [comment]
@vanpelt Hi, my docker version is 19.03.1, operating system is Linux-centos.

**Comment by chenshen03** [comment]
Any solution? Thank you very much~

**Comment by vanpelt** [comment]
@chenshen03 I would try upgrading to a newer version of docker, or running the container as the root user.  Something about your system and distribution is making the file system in the container on-writable.

**Comment by chenshen03** [comment]
@vanpelt Thank you very much and looking forward to your solution~

**Comment by chenshen03** [comment]
Any update? @vanpelt

**Comment by vanpelt** [comment]
@chenshen03 we're working on a new release that should fix this issue.  We expect it to go out this week.

**Comment by vanpelt** [comment]
@chenshen03 the latest release should fix this issue `wandb/local:0.9.46`

**Comment by chenshen03** [comment]
Thank you for your work, but the problem is still exists
![image](https://user-images.githubusercontent.com/20432947/143539709-7adfc048-2a62-4a9c-bb1e-88a1abdd30c5.png)

**Comment by vanpelt** [comment]
@chenshen03 that is a different error.  It indicates docker can't write to the filesystem that's being mounted in.  It could mean your disk is full, or it could be an error with your filesystem permissions.  Stack Overflow could be of help.

**Comment by chenshen03** [comment]
Thank you very much!

**Comment by chenshen03** [comment]
I finally solved the problem by changing the permissions of the files related to wandb under docker/overlay2.
