### ISSUE TITLE
Compatibility with tensorflow 2.0

### ISSUE THREAD

**Issue by ReinforcedMan** [wandb/client#691]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.16
* Python version: 3.7.4
* Operating System: Win 10

### Description

I try to log my custom losses using tensorboard. It seems wandb isn't compatible with the @tf.function decorator, and it would mean that using wandb would slow down the code considerably. Is tf.function supported ? 

### What I Did

```
@tf.function
def train_on_batch(self, obs1, obs2, act, rew, done, step):
[...]
   wandb.tensorflow.log('losses/q1_loss', q1_loss, step=step)
```
Error: TypeError: To be compatible with tf.contrib.eager.defun, Python functions must return zero or more Tensors; in compilation of <function create_converted_entity_factory.<locals>.create_converted_entity.<locals>.tf__log.<locals>.<lambda> at 0x000001D386C6B288>, found return value of type <class 'wandb.history.History'>, which is not a Tensor.

**Comment by vanpelt** [comment]
A quick fix would be to just use tensorboard logging then call `wandb.init(sync_tensorboard=True)`.  I'll look into to supporting @tf.function but it's unlikely to be a quick fix.

**Comment by Danmou** [comment]
@vanpelt I'm using `wandb.init(sync_tensorboard=True)` with TF 2.0 and I'm running into a different problem. Whenever a summary is written wandb spits out the following error:
```
wandb: ERROR Couldn't import tensorboard, not streaming events. Run `pip install tensorboard`
```
The error comes from [this place in the code](https://github.com/wandb/client/blob/b4ad2680d3415ee599c18d2974c144d1112ba7ec/wandb/run_manager.py#L1184-L1210). I checked it out in the debugger and the actual error is:
```
  File "/opt/pycharm-eap/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/daniel/.conda/envs/thesis2.0/lib/python3.7/site-packages/wandb/tensorboard/watcher.py", line 8, in <module>
    from tensorboard.backend.event_processing import directory_watcher
  File "/opt/pycharm-eap/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'tensorboard.backend'
```
Something weird is going on because running `from wandb.tensorboard.watcher import Watcher, Consumer` in a Python terminal works fine.

**Comment by vanpelt** [comment]
Hmm, very strange.  Can you send me the output of `pip freeze` in your conda env?  One thing to try after generating the frozen output is running `pip install tensorboard --upgrade`

**Comment by Danmou** [comment]
```
$ pip freeze
absl-py==0.8.1
argh==0.26.2
asn1crypto==0.24.0
astor==0.7.1
atomicwrites==1.3.0
attrs==19.3.0
box2d-py==2.3.8
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==1.1.1
configparser==4.0.2
cryptography==2.7
cson==0.8
cycler==0.10.0
cytoolz==0.10.1
dask==2.8.0
decorator==4.4.1
dm-control==0.0.0
dm-env==1.2
dm-tree==0.1.1
docker-pycreds==0.4.0
entrypoints==0.3
flake8==3.7.9
future==0.18.2
gast==0.2.2
gin-config==0.2.0
gitdb2==2.0.6
GitPython==3.0.5
glfw==1.8.4
google-pasta==0.1.8
gql==0.1.0
graphql-core==2.2.1
grpcio==1.23.0
gym==0.10.9
h5py==2.10.0
habitat==0.1.3
habitat-sim==0.1.3
idna==2.8
imageio==2.6.1
imageio-ffmpeg==0.3.0
importlib-metadata==0.23
isort==4.3.21
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
llvmlite==0.30.0
loguru==0.3.2
lxml==4.4.1
magnum==0.0.0
Markdown==3.1.1
matplotlib==3.1.2
mccabe==0.6.1
more-itertools==7.2.0
msal==0.4.0
mypy==0.740
mypy-extensions==0.4.3
networkx==2.4
numba==0.46.0
numpy==1.16.5
numpy-quaternion==2019.10.3.10.26.21
nvidia-ml-py3==7.352.0
oauthlib==3.0.1
olefile==0.46
opencv-python==4.1.1.26
opt-einsum==0+untagged.49.gdbede45.dirty
packaging==19.2
pathtools==0.1.2
Pillow==6.2.1
pluggy==0.13.0
promise==2.2.1
protobuf==3.10.1
psutil==5.6.5
py==1.8.0
pybullet==2.5.1
pycodestyle==2.5.0
pycparser==2.19
pyflakes==2.1.1
pyglet==1.4.7
PyJWT==1.7.1
PyOpenGL==3.1.0
pyOpenSSL==19.0.0
pyparsing==2.4.5
PyQt5==5.12.3
PyQt5-sip==4.19.18
PyQtWebEngine==5.12.1
PySocks==1.7.1
pytest==5.2.4
pytest-flake8==1.0.4
pytest-isort==0.3.1
pytest-mypy==0.4.2
pytest-runner==5.2
python-dateutil==2.8.1
PyWavelets==1.1.1
PyYAML==5.1.1
requests==2.22.0
requests-oauthlib==1.2.0
ruamel.yaml==0.16.5
ruamel.yaml.clib==0.2.0
Rx==1.6.1
scikit-image==0.16.2
scipy==1.3.2
sentry-sdk==0.13.2
shortuuid==0.5.0
six==1.13.0
smmap2==2.0.5
speg==0.3
subprocess32==3.5.4
tensorboard==2.0.0
tensorflow==2.0.0
tensorflow-estimator==2.0.0
tensorflow-probability==0.8.0rc0
termcolor==1.1.0
toolz==0.10.0
tornado==6.0.3
tqdm==4.38.0
typed-ast==1.4.0
typing-extensions==3.7.4.1
urllib3==1.25.7
wandb==0.8.16
watchdog==0.9.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
wrapt==1.11.2
yacs==0.1.6
zipp==0.6.0
```

Same problem with tensorboard 2.0.2 from pip.

**Comment by Danmou** [comment]
Minimal example:
```python
import tensorflow as tf
import wandb
wandb.init(sync_tensorboard=True)
writer = tf.summary.create_file_writer('logdir')
```

**Comment by vanpelt** [comment]
Thanks, I'll try to reproduce over the holiday.

**Comment by vanpelt** [comment]
@Danmou we have a fix, you can install with: `pip install --upgrade git+git://github.com/wandb/client.git@fix/tensorboard-import-issue#egg=wandb`

**Comment by Danmou** [comment]
The minimal example from above still gives me the same result with the fix.

**Comment by raubitsj** [comment]
@Danmou, the branch should be fixed now, there was an issue how the "pip install ...#egg=wandb" command was messing with the python environment.

Please try the:
`pip install --upgrade git+git://github.com/wandb/client.git@fix/tensorboard-import-issue#egg=wandb`
command again.  you might want to `pip uninstall wandb` first just to make sure it grabs a new version.

**Comment by Danmou** [comment]
Thanks, now it works.

**Comment by raubitsj** [comment]
This fix was released.

**Comment by jarednielsen** [comment]
Still having the same issue with TF 2.1.1 and TensorBoard 2.1.1. I run

```python
import tensorflow as tf
import wandb
wandb.init(sync_tensorboard=True)
writer = tf.summary.create_file_writer('logdir')
```

**Comment by fellhorn** [comment]
> Still having the same issue with TF 2.1.1 and TensorBoard 2.1.1. I run
> 
> ```python
> import tensorflow as tf
> import wandb
> wandb.init(sync_tensorboard=True)
> writer = tf.summary.create_file_writer('logdir')
> ```

I had the same issue when using TF and TensorBoard from the global site packages. When I switched to a venv on the machine it worked though.
