### ISSUE TITLE
Plotly Ignores Colors

### ISSUE THREAD

**Issue by intermx-rwalden** [wandb/client#778]
* Weights and Biases version: '0.8.21'
* Python version: 3.5.3
* Operating System: GCP AI Notebook with Tensorflow 2.0 Environment Jupyter Lab

### Description

If I create a bar plot using matplotlib.pyplot and pass in a set of colors to use for each bar, it displays the plot correctly with the corresponding colors. When I log this plot to wandb, the plot displayed in wandb shows the correct bars but all the same color. Alternatively, if I log the plot to wandb as an image, it uploads the plot correctly with the corresponding colors.

### What I Did

```
import numpy as np
import matplotlib.pylplot as plt
import seaborn as sns

lengths, modes = np.unique(counts, return_counts=True)
pal = list(sns.color_palette("hls", len(lengths)))
plt.bar(lengths[1:], modes[1:], color=pal)
plt.xlabel('Visit Lengths')
plt.ylabel('Frequency')
wandb.log({'Visit Length Distribution' : plt})
```

**Comment by intermx-rwalden** [comment]
In addition, when I use plotly directly, it displays perfectly in Jupyter Lab but logs a blank graph to wandb. 

```
import plotly
import plotly.graph_objects as go

plotly.offline.init_notebook_mode(connected=True)
lengths, modes = np.unique(counts, return_counts=True)
pal = list(sns.color_palette("hls", len(lengths)))
colors = ['#%02x%02x%02x' % (int(r*255), int(g*255), int(b*255)) for (r,g,b) in pal]

fig = go.Figure(data=[go.Bar(
    x=lengths[1:], 
    y=modes[1:], 
    marker_color=colors
    )])

wandb.log({'Visit Length Distribution':fig})
```

**Comment by lukas** [comment]
I think the first issue is a plotly issue.

If I do:
'''
import numpy as np
import matplotlib.pyplot as plt, mpld3
import seaborn as sns
import plotly.tools

lengths = [1,2,3,4]
modes = [1,2,3,4]
pal = list(sns.color_palette("hls", len(lengths)))
fig ,ax = plt.subplots()
ax.bar(lengths[1:], modes[1:], color=pal)
fig.xlabel('Visit Lengths')
fig.ylabel('Frequency')
plotly = plotly.tools.mpl_to_plotly(fig)
plotly
'''

I get a chart without the colors

**Comment by lukas** [comment]
https://github.com/mpld3/mpld3 seems to handle this case correctly - maybe we should switch @vanpelt - do you have any opinion?

**Comment by lukas** [comment]
the second code snippet worked great for me - I filled in some values:

```
import numpy as np
import plotly
import seaborn as sns
import plotly.graph_objects as go

wandb.init()
plotly.offline.init_notebook_mode(connected=True)
lengths, modes = [1,2,3,4], [1,2,3,4]
pal = list(sns.color_palette("hls", len(lengths)))
colors = ['#%02x%02x%02x' % (int(r*255), int(g*255), int(b*255)) for (r,g,b) in pal]

fig = go.Figure(data=[go.Bar(
    x=lengths[1:], 
    y=modes[1:], 
    marker_color=colors
    )])

wandb.log({'Visit Length Distribution':fig})
```

https://app.wandb.ai/l2k2/course-v3-nbs_dl1/runs/pru2s82n?workspace=user-l2k2

**Comment by intermx-rwalden** [comment]
I've narrowed down the issue: the cell fails when ```lengths``` and ```modes``` are initialized as numpy arrays. If I cast them into list types the plot will display correctly on the Wandb client window. Oddly enough, I can use numpy arrays and successfully display the plot in my notebook. Therefore, this likely has something to do with the way Wandb logs plots, possibly expecting only list data.

**Comment by vanpelt** [comment]
Thanks @intermx-rwalden when we serialize to json we convert numpy arrays to histograms, but I thought I had made sure that didn't happen for plotly JSON.  We clearly missed something here.

**Comment by vanpelt** [comment]
I have a branch that fixes this, you can use with: `pip install --upgrade git+git://github.com/wandb/client.git@bug/plotly_np#egg=wandb` we'll get this out in the next release.

**Comment by lukas** [comment]
This should be fixed now - thanks for the bug report!

**Comment by lorinczszabolcs** [comment]
Hi! I was facing a similar issue, when I created a seaborn scatter plot. When logging as a wandb.Image, it showed the colors, but when I logged the figure directly, the colors were not shown on the legend, only on the actual points in the scatter plot.

Example:

```
from matplotlib import pyplot as plt
import seaborn as sns

def _get_color_mapping():
    return {
        'tree': '#124A54', 'sky': '#28A2B8', 'bear': '#58C9DA',
        'bee': '#ADE68E', 'honey': '#CBFCB1'}

classes = np.array(['tree', 'sky', 'bear', 'bee', 'honey'])
fig, _ = plt.subplots(figsize=(10., 10.))
sns.scatterplot(x=np.random.random(1000), y=np.random.random(1000), hue=classes[np.random.randint(0, 5, (1000))], palette=_get_color_mapping())

wandb.log({
        "Figures/scatter": wandb.Image(fig) # works
        # "Figures/scatter": fig # colors do not appear in legend
        })
```
For info:

plotly==5.3.1
matplotlib==3.3.4
seaborn==0.11.2

**Comment by ghadialhajj** [comment]
For people who are still facing this issue with go.Scatter, it helped in my case to use `marker=go.Marker(color="blue")` (or `marker=go.scatter.Marker(color="blue")` in the later version.) when calling go.Scatter. Probably there is something similar for go.Bar.
