### ISSUE TITLE
bestmodel.pth size shrank while it was being uploaded

### ISSUE THREAD

**Issue by eugeneware** [wandb/client#844]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.8.25
* Python version: 3.7.6
* Operating System: Linux

### Description

While running a fastai callback to train a model in jupyter notebook by doing something like:

``` python
learn_clas.fit_one_cycle(10, slice(2e-3/decay_factor,2e-3), moms=moms, callbacks=WandbCallback(learn_clas))
#... do some other stuff
learn_clas.fit_one_cycle(10, slice(3e-5/decay_factor,3e-5), moms=moms, callbacks=WandbCallback(learn_clas))
```

In the results that get written out to the notebook I often see errors such as:

![image](https://user-images.githubusercontent.com/38154/73923899-b6541900-491f-11ea-873b-c83380fc0143.png)

Here's the text of the error message.

```
wandb: ERROR Error uploading "bestmodel.pth": CommError, File /home/fastai/keyword-extraction/notebooks/wandb/run-20200206_091629-h6xl4gbi/bestmodel.pth size shrank from 239376385 to 232153088 while it was being uploaded.
wandb: ERROR Error uploading "bestmodel.pth": CommError, File /home/fastai/keyword-extraction/notebooks/wandb/run-20200206_091629-h6xl4gbi/bestmodel.pth size shrank from 239376385 to 80355328 while it was being uploaded.
```
It would appear that either there's some kind of race condition - or that the file is being overwritten by the second training loop while still being uploaded by the first.

Update:

It's also happening with lots of other files, eg:

```
wandb: ERROR Error uploading "___batch_archive_1.tgz": CommError, File /tmp/tmpnn7k_ppewandb/___batch_archive_1.tgz size shrank from 416086 to 301398 while it was being uploaded.
Exception in thread Thread-78:
Traceback (most recent call last):
  File "/home/fastai/anaconda3/envs/keyword-extraction/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/fastai/anaconda3/envs/keyword-extraction/lib/python3.7/site-packages/wandb/file_pusher.py", line 85, in run
    self.cleanup_file()
  File "/home/fastai/anaconda3/envs/keyword-extraction/lib/python3.7/site-packages/wandb/file_pusher.py", line 154, in cleanup_file
    os.unlink(self.tgz_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnn7k_ppewandb/batch-1.tgz'
```

**Comment by kennazilis** [comment]
Hello! Thank you for letting us know about this error. We will take a look and get back to you as soon as we can.

**Comment by borisdayma** [comment]
Can you try to add the callback to the learner instead of at the fit step?

**Comment by borisdayma** [comment]
Also if you want to save as a separate run, you can just add a `wandb.join()` in between to close the previous run.

**Comment by eugeneware** [comment]
Thanks @borisdayma - I've been using a single learner and freezing and fine tuning it, so it's not that I'm during different runs, but the same model with multiple fine-tuning passes. But adding the callback at the learner level does seem to help the problem. I haven't seen the error once I've done that.

If I call `wandb.join()` after each fine tuning pass will that create a brand new run? I'm not sure that's what I want with the multiple fine-tuning passes I think.

**Comment by eugeneware** [comment]
Actually I'm still getting the issue, it's just happening on the `wandb.join()` that I've added at the bottom of my jupyter notebook. It doesn't seem to occur at any other place though. This is the literally the last line in my notebook:

![image](https://user-images.githubusercontent.com/38154/74919141-444efa00-541e-11ea-9528-cf387a3cb64d.png)

The error message is:

```
Exception in thread Thread-810:
Traceback (most recent call last):
  File "/home/fastai/anaconda3/envs/keyword-extraction/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/fastai/anaconda3/envs/keyword-extraction/lib/python3.7/site-packages/wandb/file_pusher.py", line 85, in run
    self.cleanup_file()
  File "/home/fastai/anaconda3/envs/keyword-extraction/lib/python3.7/site-packages/wandb/file_pusher.py", line 154, in cleanup_file
    os.unlink(self.tgz_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp6ip8rshjwandb/batch-1.tgz'
```

**Comment by borisdayma** [comment]
If you have it as a single run, you should just add the callback to the learner and you should not need any join at all but you could have one at the end 

If you save it as multiple runs, you should add it to the training loop "fit" and you will add a join after each loop.

Let me know if you still have that issue.

**Comment by ktobah** [comment]
@borisdayma 
I am having the same issue with two different scenarios:
1. I use a sweep, it was working just fine. Then suddenly, it stopped syncing and started showing the same error message. I checked the debug.log in my docker container and found:

```python
2020-04-18 19:34:02,918 INFO    MainThread:112 [run_manager.py:_sync_etc():1433] syncing files to cloud storage
2020-04-18 19:41:26,057 ERROR   Thread-21 :112 [retry.py:__call__():108] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7efd822ce550>: Failed to establish a new connection: [Errno 110] Connection timed out
```

2. I don't use a sweep, but I am trying to use Optuna for hyper-parameter optimization and log with wandb. Optuna will use 32 CPU cores, so multiple threads. I saw the same error and the same thing in debug.log.

Honestly, I am not sure if this is an internet issue from my side or something is going wrong?

**Comment by jramapuram** [comment]
I see a similar error with images:

```
wandb: ERROR Error uploading "media/images/train_mosiac-generated6_5721_c2138903.png": CommError, File /tmp/tmpd5dpje7xwandb/1cak8igk-media/images/train_mosiac-generated6_5721_c2138903.png size shrank from 459037 to 377117 while it was being uploaded.
```

**Comment by vanpelt** [comment]
Hey guys, can you try our new client library.  We're about a week away from official release, but the errors you're seeing should be fixed.  You can install with: `pip install wandb -U --pre`

**Comment by maxzzze** [comment]
> Hey guys, can you try our new client library. We're about a week away from official release, but the errors you're seeing should be fixed. You can install with: `pip install wandb -U --pre`

I am still experiencing the same issue in the original post after running the pre release install

**Comment by borisdayma** [comment]
@maxzzze Can you confirm which version of `fastai` you are using?

**Comment by maxzzze** [comment]
@borisdayma I dont see `fastai` installed

**Comment by borisdayma** [comment]
Oh sorry I thought it was a fastai related issue.
In that case how do you save your files? Do you have a simple demo?
In particular I'm interested to know if it's when you log images/data visualization or if it's when logging models.

**Comment by maxzzze** [comment]
@borisdayma I just now switched from using `optuna` to `ray` and I am not experiencing any issues like this one anymore. 

Im tunning transformers 3.5.0 now but was experiencing the above issue before using transformers 3.4.0 (optuna again).
